// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlickNodeHandle`

String generateKeypair() => RustLib.instance.api.crateBridgeGenerateKeypair();

Future<String> startNode({required String deviceName}) =>
    RustLib.instance.api.crateBridgeStartNode(deviceName: deviceName);

Future<bool> sendFlick(
        {required String content,
        required String deviceId,
        required String deviceName}) =>
    RustLib.instance.api.crateBridgeSendFlick(
        content: content, deviceId: deviceId, deviceName: deviceName);

Stream<String> incomingFlicksStream() =>
    RustLib.instance.api.crateBridgeIncomingFlicksStream();
